### ISSUE TITLE
Update broken block links after note extraction

### ISSUE THREAD

**Issue by wenlzhang** [val3344/obsidian-update-relative-links#1]
Note A may contain a block link to Note B, with something like `[[NoteB#^BlockIDB]]`. However, when extracting certain parts of Note B as a new Note C, the block link `[[NoteB#^BlockIDB]]` in Note A would not work any more because `BlockIDB` has a new note name.

Therefore, it would be great if this plugin can be used to update block IDs for such a use case. Currently, I had to manually search for BlockIDB and manually update all mentions.

**Comment by val3344** [comment]
The problem you describe is not the original intention of this plugin. This plugin subscribes to file move events and repairs broken links by comparing the paths before and after the move.

The scenario you describe is extracting part of a note into a new note, I'm not sure if Obsidian provides the relevant API. So sorry I can't help you.
