### ISSUE TITLE
高级引用中的相对路径不更新

### ISSUE THREAD

**Issue by ixxc** [val3344/obsidian-update-relative-links#4]
非常感谢作者开发这个插件

目前在使用中发现高级特性引用中的相对路径不会更新
比如：`![](../../../../test.md#^4c7e56)`，往上层目录移动时不会更新
正常往上移动三个层级应该更新为：`![](../test.md#^4c7e56)`

虽然这不是标准的markdown语法，使用相对路径的初衷也是尽可能保持笔记的通用性，但是在某些场景下还是不得不考虑使用一些高级语法来让笔记互相关联和查看

**Comment by val3344** [comment]
已经在 2.1.0 版本中解决，更一下试试。

**Comment by ixxc** [comment]
感谢修复
