### ISSUE TITLE
相对路径有点问题

### ISSUE THREAD

**Issue by jerviscui** [val3344/obsidian-update-relative-links#5]
引用页内内容时生成路径过于复杂 🤣 

下面的相对地址就是 `./`
`[页内链接](../../..//我的笔记/Tools/Markdown%20语法演示.md#页内链接)`

**Comment by jerviscui** [comment]
还有一种情况，类似下面的结构`[跳转到锚点](#aaaa)`

![image](https://github.com/val3344/obsidian-update-relative-links/assets/6396748/d94e12b0-642d-41e1-b34a-7e4e4f195c71)

格式化后会变成：

```
../../..//我的笔记/Tools/Markdown%20语法演示.md[跳转到锚点](#aaaa)
```

可以考虑跳过不进行处理。

And 上面这里是个死循环，再次执行格式化还会在前面继续添加 `../../..//我的笔...`

**Comment by val3344** [comment]
已经在 2.1.1 版本中解决，更一下试试。

**Comment by jerviscui** [comment]
这个用例没有问题了！ 👍
